spring.datasource.url=jdbc:postgresql://dpg-d7oqk0l8nd3s739mbf70-a.oregon-postgres.render.com/bugtrackerdb_0z0n

spring.datasource.username=bugtrackerdb_0z0n_user
spring.datasource.password=eJXLmoUIYgLmLwwuFgwOOH7ESSEvUUkS

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
