spring.application.name=bugtracker
#mysql configuration
spring.datasource.url=jdbc:mysql://localhost:3306/BugTracker
spring.datasource.username=root
spring.datasource.password=sandesh03
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

#JPA configuration
spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
spring.jpa.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

spring.thymeleaf.cache=false

server.port=5555
